### PR TITLE
update_media update fixes #8 #17

### LINKED ISSUE #8: Doesn`t work with more than one media type
Cant configure to work with more than one media type, could please anyone share config with working more than 1 medias to sync? (for ex.: Email and SMS). 
When I use: 

[media]
description = Email, SMS
active = 0
period = 1-7,00:00-24:00
severity = 63
onlycreate = false

I have the result when mobile phones properly inserted as Emails :(

### PR DESCRIPTION
**Pull request by ofbeaton**
fix update_media so that it doesn't erase the user's current media types, only updates/adds the one you want, side effect is it won't delete orphan media types anymore (thanks @towster)

### CODE REVIEW

**Comment by ofbeaton** [comment]
note I did not include the change to `get_mediatype_id` that @towster proposed in #17, as that caused problems in my install.

**Comment by scoopex** [comment]
Seems to be ok and to work here :-) I merge it :-)

**Comment by ofbeaton** [comment]
Thanks for merging!

**Comment by ofbeaton** [comment]
Problems with the code? I noticed it's no longer merged.

**Comment by ofbeaton** [comment]
Oh wait, I messed up the PR didn't I. I think it got merged into the `update_media` branch instead of the `master` branch. Not what I meant to submit at all. Sorry I'm not used to making PRs at all. Want me to try to resubmit against master?

**Pull request merged**
